apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
spec:
  serviceName: postgres-db-lb
  selector:
    matchLabels:
      app: postgres-db
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres-db
          image: postgres:latest
          volumeMounts:
            - name: postgres-db-volume
              mountPath: /data
          envFrom:
            - configMapRef:
                name: postgres-db-config
  # PVC
  volumeClaimTemplates:
    - metadata:
        name: postgres-db-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Mi