apiVersion: v1
kind: Service
metadata:
  name: postgres-db-lb
spec:
  selector:
    app: postgres-db
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30000
      targetPort: 5432
      name: postgresql
      protocol: TCP