apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: learn-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      volumes:
        - configMap:
            name: nginx-conf
          name: nginx-conf
#        - name: nginx-conf
#          ephemeral:
#            volumeClaimTemplate:
#              metadata:
#                labels:
#                  type: nginx-volume
#              spec:
#                accessModes: [ "ReadWriteOnce" ]
#                storageClassName: "scratch-storage-class"
#                resources:
#                  requests:
#                    storage: 10Mi
#                  limits:
#                    storage: 10Mi
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - mountPath: /etc/nginx/
              name: nginx-conf
              subPath: nginx.conf
              readOnly: true
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 5m
              memory: 10Mi
          ports:
            - containerPort: 80
              protocol: TCP

