apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: learn-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.4
          resources:
            requests:
              cpu: 5m
              memory: 10Mi
          ports:
            - containerPort: 80