apiVersion: batch/v1
kind: Job
metadata:
  name: learn-job
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
        - name: echo-hello
          image: busybox
          args:
            - /bin/sh
            - -c
            - date; echo Hello from kubernetes cluster
      restartPolicy: Never